[package]
name = "number-of-steps-to-reduce-a-number-in-binary-representation-to-one"
version = "0.1.0"
authors = ["checky <checkywho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
