[package]
name = "find-the-minimum-number-of-fibonacci-numbers-whose-sum-is-k"
version = "0.1.0"
authors = ["Checky-Hu <checkywho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
