[package]
name = "determine-whether-matrix-can-be-obtained-by-rotation"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
