[package]
name = "number-of-nodes-in-the-subtree-with-the-same-label"
version = "0.1.0"
authors = ["checky <checkywho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
