[package]
name = "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance"
version = "0.1.0"
authors = ["Checky-Hu <checkywho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
