[package]
name = "projection-area-of-3d-shapes"
version = "0.1.0"
authors = ["Checky-Hu <checky_hu@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
